export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_FORM = 'FETCH_FORM';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const ERROR = 'ERROR';
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const UPDATE_SUCCESSFUL = 'UPDATE_SUCCESSFUL';
export const DELETE = 'DELETE';
export const DELETE_SUCCESSFUL = 'DELETE_SUCCESSFUL';
export const ADD_ANSWER_SUCCESSFUL = 'ADD_ANSWER_SUCCESSFUL';
export const GET_ANSWERS = 'GET_ANSWERS';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

// =====================      Auth action types START    =========================

// load logged in user
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_UPDATE = 'LOAD_USER_UPDATE'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

//get verified user
export const VERIFIED_USER_REQUEST = 'VERIFIED_USER_REQUEST'
export const VERIFIED_USER_SUCCESS = 'VERIFIED_USER_SUCCESS'
export const VERIFIED_USER_FAIL = 'VERIFIED_USER_FAIL'
export const VERIFIED_USER_RESET = 'VERIFIED_USER_RESET'

//get unverified user
export const UNVERIFIED_USER_REQUEST = 'UNVERIFIED_USER_REQUEST'
export const UNVERIFIED_USER_SUCCESS = 'UNVERIFIED_USER_SUCCESS'
export const UNVERIFIED_USER_FAIL = 'UNVERIFIED_USER_FAIL'
export const UNVERIFIED_USER_RESET = 'UNVERIFIED_USER_RESET'

// login 
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const AUTH_RESET = 'AUTH_RESET'

// logout 
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const LOGOUT_RESET = 'LOGOUT_RESET'

// register employee
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_RESET = 'REGISTER_RESET'

// register admin
export const REGISTER_ADMIN_REQUEST = 'REGISTER_ADMIN_REQUEST'
export const REGISTER_ADMIN_SUCCESS = 'REGISTER_ADMIN_SUCCESS'
export const REGISTER_ADMIN_FAIL = 'REGISTER_ADMIN_FAIL'
export const REGISTER_ADMIN_RESET = 'REGISTER_ADMIN_RESET'

// email confirmation
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST'
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS'
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL'
export const VERIFY_EMAIL_RESET = 'VERIFY_EMAIL_RESET'

// load user 
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL = 'GET_USER_FAIL'

// send verification email 
export const RESEND_VERIFY_EMAIL_REQUEST = 'RESEND_VERIFY_EMAIL_REQUEST'
export const RESEND_VERIFY_EMAIL_SUCCESS = 'RESEND_VERIFY_EMAIL_SUCCESS'
export const RESEND_VERIFY_EMAIL_FAIL = 'RESEND_VERIFY_EMAIL_FAIL'
export const RESEND_VERIFY_EMAIL_RESET = 'RESEND_VERIFY_EMAIL_RESET'

// get user by email
export const GET_USER_BY_EMAIL_REQUEST = 'GET_USER_BY_EMAIL_REQUEST'
export const GET_USER_BY_EMAIL_SUCCESS = 'GET_USER_BY_EMAIL_SUCCESS'
export const GET_USER_BY_EMAIL_FAIL = 'GET_USER_BY_EMAIL_FAIL'
export const GET_USER_BY_EMAIL_RESET = 'GET_USER_BY_EMAIL_RESET'

// get user by email
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
export const RESET_PASSWORD_RESET = 'RESET_PASSWORD_RESET'

// show avatar preview
export const SHOW_AVATAR_PREVIEW_SUCCESS = 'SHOW_AVATAR_PREVIEW_SUCCESS'

// update USER profile
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'

// update USER profile
export const LOAD_PROFILE_REQUEST = 'LOAD_PROFILE_REQUEST'
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_PROFILE_FAIL = 'LOAD_PROFILE_FAIL'
export const LOAD_PROFILE_RESET = 'LOAD_PROFILE_RESET'

// update password
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
// =====================      Auth action types END    =========================

// load DASHBOARD
export const GET_ADMIN_DASHBOARD_REQUEST = 'GET_ADMIN_DASHBOARD_REQUEST'
export const GET_ADMIN_DASHBOARD_SUCCESS = 'GET_ADMIN_DASHBOARD_SUCCESS'
export const GET_ADMIN_DASHBOARD_FAIL = 'GET_ADMIN_DASHBOARD_FAIL'
export const CLEAR_GET_ADMIN_DASHBOARD = 'CLEAR_GET_ADMIN_DASHBOARD'

// load ADMIN DASHBOARD PROJECT
export const GET_ADMIN_DASHBOARD_PROJECT_REQUEST = 'GET_ADMIN_DASHBOARD_PROJECT_REQUEST'
export const GET_ADMIN_DASHBOARD_PROJECT_SUCCESS = 'GET_ADMIN_DASHBOARD_PROJECT_SUCCESS'
export const GET_ADMIN_DASHBOARD_PROJECT_FAIL = 'GET_ADMIN_DASHBOARD_PROJECT_FAIL'
export const CLEAR_GET_ADMIN_DASHBOARD_PROJECT = 'CLEAR_GET_ADMIN_DASHBOARD_PROJECT'



// =====================   driver action types Start   =========================
// load driver
export const LOAD_DRIVER_REQUEST = 'LOAD_DRIVER_REQUEST'
export const LOAD_DRIVER_SUCCESS = 'LOAD_DRIVER_SUCCESS'
export const LOAD_DRIVER_FAIL = 'LOAD_DRIVER_FAIL'
export const LOAD_DRIVER_RESET = 'LOAD_DRIVER_RESET'
// load DRIVER
export const GET_DRIVER_REQUEST = 'GET_DRIVER_REQUEST'
export const GET_DRIVER_SUCCESS = 'GET_DRIVER_SUCCESS'
export const GET_DRIVER_FAIL = 'GET_DRIVER_FAIL'
export const CLEAR_GET_DRIVERS = 'CLEAR_GET_DRIVERS'
// Create User
export const CREATE_DRIVER_REQUEST = 'CREATE_DRIVER_REQUEST'
export const CREATE_DRIVER_SUCCESS = 'CREATE_DRIVER_SUCCESS'
export const CREATE_DRIVER_FAIL = 'CREATE_DRIVER_FAIL'
export const CLEAR_DRIVER = 'CLEAR_DRIVER'
// delete DRIVER
export const DELETE_DRIVER_REQUEST = 'DELETE_DRIVER_REQUEST'
export const DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS'
export const DELETE_DRIVER_FAIL = 'DELETE_DRIVER_FAIL'
export const DELETE_DRIVER_RESET = 'DELETE_DRIVER_RESET'
// update DRIVER
export const UPDATE_DRIVER_REQUEST = 'UPDATE_DRIVER_REQUEST'
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS'
export const UPDATE_DRIVER_FAIL = 'UPDATE_DRIVER_FAIL'
export const UPDATE_DRIVER_RESET = 'UPDATE_DRIVER_RESET'
// =====================  Ends Client action types Start   =========================
// =====================   VEHICLE action types Start   =========================
// load VEHICLE
export const GET_VEHICLE_REQUEST = 'GET_VEHICLE_REQUEST'
export const GET_VEHICLE_SUCCESS = 'GET_VEHICLE_SUCCESS'
export const GET_VEHICLE_FAIL = 'GET_VEHICLE_FAIL'
export const CLEAR_GET_VEHICLES = 'CLEAR_GET_VEHICLES'
// Create User
export const CREATE_VEHICLE_REQUEST = 'CREATE_VEHICLE_REQUEST'
export const CREATE_VEHICLE_SUCCESS = 'CREATE_VEHICLE_SUCCESS'
export const CREATE_VEHICLE_FAIL = 'CREATE_VEHICLE_FAIL'
export const CLEAR_VEHICLE = 'CLEAR_VEHICLE'
// delete VEHICLE
export const DELETE_VEHICLE_REQUEST = 'DELETE_VEHICLE_REQUEST'
export const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS'
export const DELETE_VEHICLE_FAIL = 'DELETE_VEHICLE_FAIL'
export const DELETE_VEHICLE_RESET = 'DELETE_VEHICLE_RESET'
// load driver
export const LOAD_VEHICLE_REQUEST = 'LOAD_VEHICLE_REQUEST'
export const LOAD_VEHICLE_SUCCESS = 'LOAD_VEHICLE_SUCCESS'
export const LOAD_VEHICLE_FAIL = 'LOAD_VEHICLE_FAIL'
export const LOAD_VEHICLE_RESET = 'LOAD_VEHICLE_RESET'
// update VEHICLE
export const UPDATE_VEHICLE_REQUEST = 'UPDATE_VEHICLE_REQUEST'
export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS'
export const UPDATE_VEHICLE_FAIL = 'UPDATE_VEHICLE_FAIL'
export const UPDATE_VEHICLE_RESET = 'UPDATE_VEHICLE_RESET'
// =====================  Ends VEHICLE action types Start   =========================
// =====================   ELD_DEVICES action types Start   =========================
// load ELD_DEVICES
export const GET_ELD_DEVICES_REQUEST = 'GET_ELD_DEVICES_REQUEST'
export const GET_ELD_DEVICES_SUCCESS = 'GET_ELD_DEVICES_SUCCESS'
export const GET_ELD_DEVICES_FAIL = 'GET_ELD_DEVICES_FAIL'
export const CLEAR_GET_ELD_DEVICESS = 'CLEAR_GET_ELD_DEVICESS'
// Create User
export const CREATE_ELD_DEVICES_REQUEST = 'CREATE_ELD_DEVICES_REQUEST'
export const CREATE_ELD_DEVICES_SUCCESS = 'CREATE_ELD_DEVICES_SUCCESS'
export const CREATE_ELD_DEVICES_FAIL = 'CREATE_ELD_DEVICES_FAIL'
export const CLEAR_ELD_DEVICES = 'CLEAR_ELD_DEVICES'
// delete ELD_DEVICES
export const DELETE_ELD_DEVICES_REQUEST = 'DELETE_ELD_DEVICES_REQUEST'
export const DELETE_ELD_DEVICES_SUCCESS = 'DELETE_ELD_DEVICES_SUCCESS'
export const DELETE_ELD_DEVICES_FAIL = 'DELETE_ELD_DEVICES_FAIL'
export const DELETE_ELD_DEVICES_RESET = 'DELETE_ELD_DEVICES_RESET'
// load driver
export const LOAD_ELD_DEVICES_REQUEST = 'LOAD_ELD_DEVICES_REQUEST'
export const LOAD_ELD_DEVICES_SUCCESS = 'LOAD_ELD_DEVICES_SUCCESS'
export const LOAD_ELD_DEVICES_FAIL = 'LOAD_ELD_DEVICES_FAIL'
export const LOAD_ELD_DEVICES_RESET = 'LOAD_ELD_DEVICES_RESET'
// update ELD_DEVICES
export const UPDATE_ELD_DEVICES_REQUEST = 'UPDATE_ELD_DEVICES_REQUEST'
export const UPDATE_ELD_DEVICES_SUCCESS = 'UPDATE_ELD_DEVICES_SUCCESS'
export const UPDATE_ELD_DEVICES_FAIL = 'UPDATE_ELD_DEVICES_FAIL'
export const UPDATE_ELD_DEVICES_RESET = 'UPDATE_ELD_DEVICES_RESET'
// =====================  Ends ELD_DEVICES action types Start   =========================
// =====================   USER action types Start   =========================
// load USER
export const LOAD_USERS_REQUEST = 'LOAD_USERS_REQUEST'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL'
export const LOAD_USERS_RESET = 'LOAD_USERS_RESET'
// load USER
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const CLEAR_GET_USERS = 'CLEAR_GET_USERS'
// Create User
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
export const CLEAR_USER = 'CLEAR_USER'
// delete USER
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'
// update USER
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'
// =====================  Ends USER action types Start   =========================
