// =====================      Dashboard action types START    =========================

export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_FAIL = 'GET_PROJECT_FAIL'
export const CLEAR_GET_PROJECTS = 'CLEAR_GET_PROJECTS'
// PROJECT MEMBERS
export const GET_PROJECT_MEMBER_REQUEST = 'GET_PROJECT_MEMBER_REQUEST'
export const GET_PROJECT_MEMBER_SUCCESS = 'GET_PROJECT_MEMBER_SUCCESS'
export const GET_PROJECT_MEMBER_FAIL = 'GET_PROJECT_MEMBER_FAIL'
// PROJECT OBJECTIVE
export const PROJECT_OBJECTIVE_TYPES_REQUEST = 'PROJECT_OBJECTIVE_TYPES_REQUEST'
export const PROJECT_OBJECTIVE_TYPES_SUCCESS = 'PROJECT_OBJECTIVE_TYPES_SUCCESS'
export const PROJECT_OBJECTIVE_TYPES_FAIL = 'PROJECT_OBJECTIVE_TYPES_FAIL'

